version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - "8080:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/conf:/etc/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  nodejs:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: nodejs
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
